# Generated by Django 5.2.4 on 2025-07-16 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=255, verbose_name='Команда')),
                ('national_team', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сборная')),
                ('brand', models.CharField(max_length=100, verbose_name='Бренд')),
                ('season', models.CharField(max_length=50, verbose_name='Сезон')),
                ('kit_type', models.CharField(max_length=100, verbose_name='Тип формы')),
                ('condition', models.FloatField(default='5', max_length=50, verbose_name='Состояние')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('size', models.CharField(max_length=50, verbose_name='Размер')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('features', models.TextField(blank=True, null=True, verbose_name='Особенности')),
                ('contacts', models.CharField(max_length=255, verbose_name='Контакты')),
                ('hashtags', models.CharField(blank=True, max_length=255, null=True, verbose_name='Хештеги')),
                ('post_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на пост')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Картинка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_set', to='products.product', verbose_name='Продукт')),
            ],
        ),
    ]
