# Generated by Django 5.2.4 on 2025-08-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(default='Новая', max_length=50, verbose_name='Состояние'),
        ),
    ]
