# Generated by Django 5.2.4 on 2025-08-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_image_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.JSONField(blank=True, default=list, verbose_name='Изображения'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
