# Generated by Django 5.2.5 on 2025-09-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_remove_product_images_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="league",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Лига"
            ),
        ),
    ]
